import type { Localized } from "@/lib/i18n";
import type { HoodId } from "./neighbourhoods";
import type { PlanKey } from "./plans";
import type { AgentId } from "./agents";

export type Deal = "sale" | "rent";
export type PropertyType = "apartment" | "studio" | "penthouse" | "loft" | "house";
export type Feature = "terrace" | "parking" | "elevator" | "registered" | "garden" | "pool" | "ac" | "furnished" | "storage";
export type Badge = "new" | "exclusive" | "reserved";

export type Listing = {
  id: string;
  slug: Localized<string>;
  deal: Deal;
  type: PropertyType;
  hood: HoodId;
  street: string;
  /** Position on the Novi Sad SVG map (viewBox 1000×700). */
  at: [number, number];
  /** EUR; monthly for rentals. */
  price: number;
  area: number;
  terrace?: number;
  plot?: number;
  rooms: number;
  floor: number;
  floors: number;
  year: number;
  renovated?: number;
  heating: "district" | "gas" | "heatpump" | "floor";
  features: Feature[];
  agent: AgentId;
  badge?: Badge;
  plan: PlanKey;
  listed: string;
  title: Localized<string>;
  summary: Localized<string>;
  description: Localized<string[]>;
  photos: Localized<string>[];
};

const p = <T,>(sr: T, en: T) => ({ sr, en });

export const listings: Listing[] = [
  {
    id: "l01",
    slug: { sr: "trosoban-stan-suncani-kej-liman", en: "three-bedroom-flat-sunny-quay-liman" },
    deal: "sale",
    type: "apartment",
    hood: "liman",
    street: "Sunčani kej",
    at: [515, 497],
    price: 289000,
    area: 84,
    terrace: 11,
    rooms: 3.0,
    floor: 6,
    floors: 8,
    year: 2021,
    heating: "floor",
    features: ["terrace", "parking", "elevator", "registered", "ac", "storage"],
    agent: "ana",
    badge: "new",
    plan: "three",
    listed: "2026-09-18",
    title: p("Trosoban stan na Sunčanom keju", "Three-room flat on the Sunny Quay"),
    summary: p(
      "Teraco, orah i Dunav u prozoru. Šesti sprat, garažno mesto i podno grejanje.",
      "Terrazzo, walnut and the Danube in the window. Sixth floor, garage space and underfloor heating.",
    ),
    description: p(
      [
        "Stan je uređen po projektu enterijera prošle godine i nikada nije izdavan. Kuhinjsko ostrvo od teraca, zidovi obloženi orahom i veliki prozori ka keju daju mu mir hotelskog apartmana, ali sa ormarima kakve svaka porodica treba.",
        "Zgrada iz 2021. ima dva lifta, podzemnu garažu i video nadzor. Štrand je na sedam minuta hoda, SPENS na dvanaest. Garažno mesto i ostava od 4 m² ulaze u cenu.",
      ],
      [
        "The flat was fitted out to an interior designer's plan last year and has never been let. A terrazzo kitchen island, walnut-panelled walls and tall windows onto the quay give it the calm of a hotel suite, with the storage a family actually needs.",
        "The 2021 building has two lifts, an underground garage and CCTV. Štrand beach is a seven-minute walk, SPENS twelve. A garage space and a 4 m² storage room are included in the price.",
      ],
    ),
    photos: [
      p("Dnevna soba sa kuhinjskim ostrvom od teraca", "Living room with a terrazzo kitchen island"),
      p("Dnevni boravak i trpezarija", "Living and dining area"),
      p("Kuhinjsko ostrvo sa barskim stolicama", "Kitchen island with bar stools"),
      p("Ugao dnevne sobe uz prozor", "Living room corner by the window"),
      p("Kuhinja otvorena ka dnevnom boravku", "Kitchen open to the living room"),
      p("Radna ploča od teraca", "Terrazzo worktop"),
      p("Spavaća soba sa zidom od oraha", "Bedroom with a walnut wall"),
      p("Glavna spavaća soba", "Main bedroom"),
      p("Kupatilo od teraca i oraha", "Terrazzo and walnut bathroom"),
      p("Sudopera i radna ploča", "Sink and worktop"),
      p("Hodnik sa lukom", "Arched hallway"),
      p("Dnevna soba sa biljkama", "Living room with plants"),
    ],
  },
  {
    id: "l02",
    slug: { sr: "garsonjera-dunavska-stari-grad", en: "studio-dunavska-old-town" },
    deal: "sale",
    type: "studio",
    hood: "stari-grad",
    street: "Dunavska",
    at: [575, 394],
    price: 112000,
    area: 34,
    rooms: 0.5,
    floor: 2,
    floors: 3,
    year: 1908,
    renovated: 2023,
    heating: "gas",
    features: ["registered", "ac", "furnished"],
    agent: "marija",
    plan: "studio",
    listed: "2026-09-02",
    title: p("Garsonjera sa riblja kost parketom kod Dunavskog parka", "Herringbone studio by the Danube Park"),
    summary: p("34 m² u zgradi iz 1908, potpuno renovirano. Dunavski park je preko puta.", "34 m² in a 1908 building, fully renovated. The Danube Park is across the street."),
    description: p(
      [
        "Renovacija 2023. je rađena do zida: nove instalacije, gasno etažno grejanje, parket riblja kost od hrasta i ugradni nameštaj po meri koji krije krevet, radni sto i ormar. Plafon je visok 3,4 m.",
        "Idealno kao prvi stan ili za izdavanje: slični stanovi u ulici se izdaju za 480–550 € mesečno. Prodaje se sa nameštajem.",
      ],
      [
        "The 2023 renovation went back to the walls: new wiring and plumbing, gas heating, oak herringbone parquet and bespoke joinery that hides a bed, a desk and a wardrobe. The ceiling is 3.4 m high.",
        "Ideal as a first home or a rental: similar flats on the street let for €480–550 a month. Sold furnished.",
      ],
    ),
    photos: [
      p("Otvoren prostor sa kuhinjom", "Open-plan space with kitchen"),
      p("Radni i trpezarijski deo", "Work and dining corner"),
      p("Trpezarijski sto ispod lampe", "Dining table under a pendant"),
      p("Sofa i sto za kafu", "Sofa and coffee table"),
      p("Ugradna niša sa radnim stolom", "Built-in desk niche"),
      p("Hodnik sa parketom riblja kost", "Hallway with herringbone parquet"),
      p("Kupatilo", "Bathroom"),
      p("Detalj trpezarije", "Dining detail"),
    ],
  },
  {
    id: "l03",
    slug: { sr: "jednoiposoban-stan-detelinara", en: "one-bedroom-flat-detelinara" },
    deal: "sale",
    type: "apartment",
    hood: "detelinara",
    street: "Bulevar Jaše Tomića",
    at: [300, 230],
    price: 104000,
    area: 41,
    rooms: 1.5,
    floor: 3,
    floors: 5,
    year: 1978,
    renovated: 2024,
    heating: "district",
    features: ["registered", "ac", "storage"],
    agent: "ana",
    plan: "onehalf",
    listed: "2026-08-27",
    title: p("Svetao jednoiposoban stan na Detelinari", "Bright one-bedroom flat in Detelinara"),
    summary: p("Renoviran 2024, okrenut jugu, 41 m². Useljiv odmah.", "Renovated in 2024, south-facing, 41 m². Ready to move in."),
    description: p(
      [
        "Stan je okrenut jugu i ima sunce od jutra do kasnog popodneva. Renoviran je prošle godine: novi prozori, kupatilo, podovi i kuhinja. Polusoba je dovoljno velika za dečji krevetac ili radni kutak.",
        "Škola i vrtić su u istom bloku, pijaca Detelinara na pet minuta. Mesečni troškovi su oko 95 € uključujući grejanje.",
      ],
      [
        "The flat faces south and gets sun from morning to late afternoon. It was renovated last year: new windows, bathroom, floors and kitchen. The half room is big enough for a cot or a home office.",
        "A school and a nursery are on the same block, the Detelinara market five minutes away. Monthly costs are about €95 including heating.",
      ],
    ),
    photos: [
      p("Dnevna soba okrenuta jugu", "South-facing living room"),
      p("Postavljen trpezarijski sto", "Set dining table"),
      p("Sofa u dnevnoj sobi", "Living room sofa"),
      p("Trpezarija uz prozor", "Dining by the window"),
      p("Kutak za čitanje", "Reading corner"),
      p("Dnevna soba", "Living room"),
      p("Spavaći deo", "Sleeping area"),
    ],
  },
  {
    id: "l04",
    slug: { sr: "dvoiposoban-stan-temerinska-podbara", en: "two-bedroom-period-flat-podbara" },
    deal: "sale",
    type: "apartment",
    hood: "podbara",
    street: "Temerinska",
    at: [690, 282],
    price: 189000,
    area: 71,
    rooms: 2.5,
    floor: 1,
    floors: 2,
    year: 1912,
    renovated: 2022,
    heating: "gas",
    features: ["registered", "ac", "storage"],
    agent: "marija",
    badge: "exclusive",
    plan: "twohalf",
    listed: "2026-09-10",
    title: p("Stan u austrougarskoj zgradi sa ciglom i crnim prozorima", "Period flat with exposed brick and black steel windows"),
    summary: p("Visoki plafoni, originalna cigla i novi čelični prozori. Podbara, prvi sprat.", "High ceilings, original brick and new steel windows. Podbara, first floor."),
    description: p(
      [
        "Vlasnici, arhitektonski par, sačuvali su dimnjak i zidove od cigle iz 1912. i ubacili sve što stari stanovi obično nemaju: podno grejanje u kupatilu, dvostruko staklo i kuhinju od 4,6 metara.",
        "Zgrada ima samo četiri stana i zajedničko dvorište sa orahom. Dunav je na kraju ulice, centar na deset minuta peške.",
      ],
      [
        "The owners, an architect couple, kept the 1912 chimney breast and brick walls and added everything old flats usually lack: underfloor heating in the bathroom, double glazing and a 4.6-metre kitchen.",
        "The building has only four flats and a shared courtyard with a walnut tree. The Danube is at the end of the street, the centre ten minutes' walk away.",
      ],
    ),
    photos: [
      p("Dnevna soba i trpezarija sa crnim prozorima", "Living and dining with black windows"),
      p("Stub od cigle i ogledalo", "Brick column and mirror"),
      p("Sofa pored zida od cigle", "Sofa beside the brick wall"),
      p("Kuhinja i dnevni boravak", "Kitchen and living area"),
      p("Trpezarijski sto i kuhinja", "Dining table and kitchen"),
      p("Ulaz sa ciglom", "Entrance with brick"),
      p("Detalj prozora", "Window detail"),
      p("Kuhinja od 4,6 m", "The 4.6 m kitchen"),
    ],
  },
  {
    id: "l05",
    slug: { sr: "moderna-kuca-sremska-kamenica", en: "modern-house-sremska-kamenica" },
    deal: "sale",
    type: "house",
    hood: "sremska-kamenica",
    street: "Vojvode Putnika",
    at: [330, 662],
    price: 465000,
    area: 218,
    plot: 620,
    rooms: 5.0,
    floor: 0,
    floors: 2,
    year: 2022,
    heating: "heatpump",
    features: ["garden", "parking", "terrace", "registered", "ac", "storage"],
    agent: "nikola",
    badge: "new",
    plan: "house",
    listed: "2026-09-21",
    title: p("Moderna kuća sa baštom u Sremskoj Kamenici", "Modern house with a garden in Sremska Kamenica"),
    summary: p("218 m², plac 620 m², toplotna pumpa i garaža za dva auta. Useljiva 2022.", "218 m², 620 m² plot, heat pump and a double garage. Completed 2022."),
    description: p(
      [
        "Kuća je projektovana za porodicu od četvoro: prizemlje je jedan veliki prostor okrenut bašti, sprat ima tri spavaće sobe i dva kupatila. Fasada od tamne opeke i ariša, prozori od poda do plafona.",
        "Grejanje i hlađenje su na toplotnu pumpu, pa je račun za struju zimi oko 140 €. Do Mosta slobode je šest minuta vožnje, do škole u Kamenici četiri.",
      ],
      [
        "The house was designed for a family of four: the ground floor is one large space facing the garden, upstairs has three bedrooms and two bathrooms. Dark brick and larch façade, floor-to-ceiling windows.",
        "Heating and cooling run on a heat pump, so the winter electricity bill is around €140. The Liberty Bridge is a six-minute drive, the Kamenica school four.",
      ],
    ),
    photos: [
      p("Kuća sa ulice", "The house from the street"),
      p("Dnevni boravak sa pogledom na baštu", "Living room overlooking the garden"),
      p("Kuhinja sa ostrvom", "Kitchen with island"),
      p("Ulaz i stakleno stepenište", "Entrance and glass staircase"),
      p("Kuhinja otvorena ka bašti", "Kitchen open to the garden"),
      p("Dnevna soba", "Living room"),
      p("Trpezarija", "Dining room"),
      p("Lebdeće stepenice", "Floating staircase"),
      p("Kupatilo sa kadom", "Bathroom with a freestanding tub"),
      p("Tuš kabina od mermera", "Marble shower"),
      p("Fasada i garaža", "Façade and garage"),
      p("Ulazni trem", "Entrance porch"),
    ],
  },
  {
    id: "l06",
    slug: { sr: "porodicna-kuca-petrovaradin", en: "family-house-petrovaradin" },
    deal: "sale",
    type: "house",
    hood: "petrovaradin",
    street: "Preradovićeva",
    at: [792, 520],
    price: 520000,
    area: 245,
    plot: 800,
    rooms: 5.5,
    floor: 0,
    floors: 2,
    year: 2019,
    heating: "gas",
    features: ["garden", "parking", "terrace", "registered", "ac", "storage"],
    agent: "nikola",
    plan: "house",
    listed: "2026-08-15",
    title: p("Porodična kuća sa velikom kuhinjom ispod tvrđave", "Family house with a chef's kitchen below the fortress"),
    summary: p("245 m² na placu od 800 m². Kuhinja od 32 m², kamin i pogled na tvrđavu.", "245 m² on an 800 m² plot. A 32 m² kitchen, fireplace and fortress views."),
    description: p(
      [
        "Srce kuće je kuhinja: ostrvo od kvarca dugačko 3,8 metara, dve rerne i trpezarija za dvanaest. Dnevna soba ima kamin na drva i visok plafon sa gredama.",
        "Na spratu su četiri spavaće sobe, od kojih glavna ima garderober i kupatilo. Bašta je ograđena, sa pristupom za dva automobila. Tvrđava je na sedam minuta hoda.",
      ],
      [
        "The heart of the house is the kitchen: a 3.8-metre quartz island, two ovens and dining for twelve. The living room has a wood-burning fireplace and a high beamed ceiling.",
        "Upstairs are four bedrooms, the main one with a walk-in wardrobe and en-suite. The garden is fenced, with access for two cars. The fortress is a seven-minute walk.",
      ],
    ),
    photos: [
      p("Kuhinjsko ostrvo i izlaz u baštu", "Kitchen island and garden doors"),
      p("Kuhinja i trpezarija", "Kitchen and dining"),
      p("Kuhinja sa kvarcnim ostrvom", "Kitchen with quartz island"),
      p("Pogled preko ostrva", "View across the island"),
      p("Barske stolice uz ostrvo", "Bar stools at the island"),
      p("Trpezarija za dvanaest", "Dining for twelve"),
      p("Sudopera ispod prozora", "Sink under the window"),
      p("Glavna spavaća soba", "Main bedroom"),
      p("Dnevna soba sa kaminom", "Living room with fireplace"),
      p("Dnevna soba sa visokim plafonom", "Living room with a high ceiling"),
      p("Kupatilo sa zelenim ormarićem", "Bathroom with a green vanity"),
    ],
  },
  {
    id: "l07",
    slug: { sr: "dvosoban-stan-izdavanje-liman", en: "two-room-flat-to-rent-liman" },
    deal: "rent",
    type: "apartment",
    hood: "liman",
    street: "Balzakova",
    at: [398, 482],
    price: 850,
    area: 62,
    terrace: 8,
    rooms: 2.0,
    floor: 4,
    floors: 9,
    year: 2017,
    heating: "district",
    features: ["terrace", "elevator", "registered", "ac", "furnished", "parking"],
    agent: "stefan",
    plan: "two",
    listed: "2026-09-24",
    title: p("Namešten dvosoban stan sa terasom, Liman III", "Furnished two-room flat with terrace, Liman III"),
    summary: p("Svetao, prirodni materijali, terasa od 8 m². Dostupan od 1. novembra.", "Bright, natural materials, an 8 m² balcony. Available from 1 November."),
    description: p(
      [
        "Stan je opremljen u prirodnim materijalima: rattan, lan, hrastov sto. Sve je novo od 2025. Veš-mašina, sudo-mašina i klima u obe sobe.",
        "Najam je 850 € mesečno plus režije (oko 110 €). Depozit jedna kirija, minimalno godinu dana. Kućni ljubimci po dogovoru.",
      ],
      [
        "The flat is furnished in natural materials: rattan, linen, an oak table. Everything is new since 2025. Washing machine, dishwasher and air conditioning in both rooms.",
        "Rent is €850 a month plus utilities (about €110). One month's deposit, twelve-month minimum. Pets by arrangement.",
      ],
    ),
    photos: [
      p("Dnevna soba u prirodnim materijalima", "Living room in natural materials"),
      p("Dnevni boravak i trpezarija", "Living and dining"),
      p("Sofa i hrastov sto", "Sofa and oak table"),
      p("Detalj stola za kafu", "Coffee table detail"),
      p("Trpezarija", "Dining area"),
      p("Fotelja u uglu", "Armchair in the corner"),
    ],
  },
  {
    id: "l08",
    slug: { sr: "dvosoban-stan-novogradnja-grbavica", en: "two-room-new-build-grbavica" },
    deal: "sale",
    type: "apartment",
    hood: "grbavica",
    street: "Gogoljeva",
    at: [352, 362],
    price: 158000,
    area: 56,
    terrace: 6,
    rooms: 2.0,
    floor: 3,
    floors: 5,
    year: 2020,
    heating: "district",
    features: ["terrace", "elevator", "registered", "parking", "ac"],
    agent: "ana",
    plan: "two",
    listed: "2026-09-05",
    title: p("Dvosoban stan u novogradnji, Grbavica", "Two-room flat in a new build, Grbavica"),
    summary: p("Uknjižen, 56 m², treći sprat sa liftom i parking mestom u dvorištu.", "Registered, 56 m², third floor with lift and a courtyard parking space."),
    description: p(
      [
        "Kuhinja i dnevna soba su jedan svetao prostor, spavaća soba gleda u dvorište. Stan ima svetle hrastove podove, belu kuhinju i terasu na zapad.",
        "Zgrada iz 2020. ima samo 14 stanova. Promenada je na sedam minuta, Bulevar oslobođenja na četiri. Idealno za par ili investiciju: izdaje se za 600–650 €.",
      ],
      [
        "The kitchen and living room form one bright space; the bedroom looks onto the courtyard. Pale oak floors, a white kitchen and a west-facing balcony.",
        "The 2020 building has only 14 flats. Promenada mall is seven minutes away, Liberation Boulevard four. Ideal for a couple or as an investment: it lets for €600–650.",
      ],
    ),
    photos: [
      p("Dnevna soba i kuhinja", "Living room and kitchen"),
      p("Dnevni boravak", "Living area"),
      p("Bela kuhinja", "White kitchen"),
      p("Kuhinjski elementi", "Kitchen units"),
      p("Ulaz i trpezarijski kutak", "Entrance and dining nook"),
      p("Kupatilo", "Bathroom"),
      p("Dnevna soba uz prozor", "Living room by the window"),
    ],
  },
  {
    id: "l09",
    slug: { sr: "trosoban-porodicni-stan-novo-naselje", en: "three-room-family-flat-novo-naselje" },
    deal: "sale",
    type: "apartment",
    hood: "novo-naselje",
    street: "Bulevar Slobodana Jovanovića",
    at: [160, 330],
    price: 199000,
    area: 81,
    terrace: 9,
    rooms: 3.0,
    floor: 5,
    floors: 8,
    year: 2008,
    renovated: 2025,
    heating: "district",
    features: ["terrace", "elevator", "registered", "parking", "storage"],
    agent: "stefan",
    plan: "three",
    listed: "2026-08-30",
    title: p("Trosoban porodični stan sa dve terase", "Three-room family flat with two balconies"),
    summary: p("81 m², dve spavaće sobe, garažno mesto. Škola i park ispred zgrade.", "81 m², two bedrooms, a garage space. School and park in front of the building."),
    description: p(
      [
        "Renoviran 2025. u toplim neutralnim tonovima. Dnevna soba od 26 m² izlazi na terasu, a kuhinja ima trpezariju za šestoro. Obe spavaće sobe su okrenute parku.",
        "Novo naselje ima najviše parkinga u gradu i najveće parkove. Garažno mesto u podrumu zgrade je uključeno u cenu.",
      ],
      [
        "Renovated in 2025 in warm neutral tones. The 26 m² living room opens onto a balcony and the kitchen seats six. Both bedrooms face the park.",
        "Novo naselje has the most parking in town and the biggest parks. A garage space in the building's basement is included.",
      ],
    ),
    photos: [
      p("Dnevna soba sa ugaonom garniturom", "Living room with corner sofa"),
      p("Dnevna soba sa ogledalom", "Living room with a round mirror"),
      p("Kutak za odmor", "Lounge corner"),
      p("Spavaća soba", "Bedroom"),
      p("Kuhinja i trpezarija", "Kitchen and dining"),
      p("Trpezarija za šestoro", "Dining for six"),
      p("Kupatilo", "Bathroom"),
    ],
  },
  {
    id: "l10",
    slug: { sr: "salonski-stan-pasiceva-stari-grad", en: "grand-salon-flat-old-town" },
    deal: "sale",
    type: "apartment",
    hood: "stari-grad",
    street: "Pašićeva",
    at: [520, 318],
    price: 395000,
    area: 128,
    rooms: 4.0,
    floor: 2,
    floors: 3,
    year: 1896,
    renovated: 2021,
    heating: "gas",
    features: ["registered", "elevator", "ac", "storage"],
    agent: "jelena",
    badge: "exclusive",
    plan: "four",
    listed: "2026-09-12",
    title: p("Salonski četvorosoban stan sa štukaturom", "Grand four-room salon flat with plasterwork"),
    summary: p("128 m², plafoni 3,6 m, originalna štukatura i hrastov parket. Pet minuta do Trga.", "128 m², 3.6 m ceilings, original plasterwork and oak parquet. Five minutes to the square."),
    description: p(
      [
        "Jedan od retkih salonskih stanova u centru koji je sačuvao sve: štukaturu, dvokrilna vrata, kaljevu peć u salonu i parket riblja kost. Renovacija 2021. je dodala lift u zgradu, nove instalacije i kuhinju.",
        "Salon i trpezarija su povezani, pa stan prima 20 gostiju. Radna soba ima ugrađenu biblioteku. Prodaja isključivo preko naše agencije.",
      ],
      [
        "One of the few salon flats in the centre that kept everything: plasterwork, double doors, a tiled stove in the salon and herringbone parquet. The 2021 renovation added a lift to the building, new services and a kitchen.",
        "The salon and dining room connect, so the flat hosts twenty guests. The study has a built-in library. Sold exclusively through our agency.",
      ],
    ),
    photos: [
      p("Trpezarija sa lusterom i parketom riblja kost", "Dining room with chandelier and herringbone parquet"),
      p("Salon sa visokim prozorima", "Salon with tall windows"),
      p("Dnevna soba sa plavim zidom", "Living room with a blue wall"),
      p("Salon sa slikom", "Salon with a painting"),
      p("Francuski prozor", "French window"),
      p("Trpezarija sa zelenim zidovima", "Green dining room"),
      p("Radna soba sa bibliotekom", "Study with a library"),
    ],
  },
  {
    id: "l11",
    slug: { sr: "penthaus-sa-terasom-centar", en: "penthouse-with-roof-terrace-centre" },
    deal: "sale",
    type: "penthouse",
    hood: "stari-grad",
    street: "Bulevar Mihajla Pupina",
    at: [598, 420],
    price: 360000,
    area: 102,
    terrace: 38,
    rooms: 3.0,
    floor: 7,
    floors: 7,
    year: 2018,
    heating: "floor",
    features: ["terrace", "elevator", "registered", "parking", "ac"],
    agent: "jelena",
    plan: "three",
    listed: "2026-09-16",
    title: p("Penthaus sa terasom od 38 m² nad centrom", "Penthouse with a 38 m² roof terrace"),
    summary: p("Sedmi sprat, terasa pogleda na tvrđavu i Dunav, dva parking mesta.", "Seventh floor, terrace facing the fortress and the Danube, two parking spaces."),
    description: p(
      [
        "Terasa od 38 m² gleda na Petrovaradinsku tvrđavu i Varadinski most. Leti je to druga dnevna soba: ima struju, vodu i tendu na motor.",
        "Unutra su dnevna soba sa erkerom, dve spavaće sobe i dva kupatila. Zgrada ima recepciju i dva parking mesta u garaži koja pripadaju stanu.",
      ],
      [
        "The 38 m² terrace looks over Petrovaradin Fortress and the Varadin Bridge. In summer it's a second living room, with power, water and a motorised awning.",
        "Inside are a living room with a bay window, two bedrooms and two bathrooms. The building has a concierge, and two garage spaces belong to the flat.",
      ],
    ),
    photos: [
      p("Dnevna soba sa erkerom", "Living room with a bay window"),
      p("Dnevni boravak", "Living area"),
      p("Vrata ka terasi", "Doors to the terrace"),
      p("Krovna terasa", "Roof terrace"),
      p("Terasa sa biljkama", "Balcony with plants"),
      p("Spavaća soba", "Bedroom"),
    ],
  },
  {
    id: "l12",
    slug: { sr: "loft-sa-galerijom-petrovaradin", en: "loft-with-gallery-petrovaradin" },
    deal: "sale",
    type: "loft",
    hood: "petrovaradin",
    street: "Beogradska",
    at: [680, 570],
    price: 238000,
    area: 96,
    rooms: 2.5,
    floor: 2,
    floors: 2,
    year: 1930,
    renovated: 2022,
    heating: "heatpump",
    features: ["registered", "ac", "parking"],
    agent: "nikola",
    badge: "reserved",
    plan: "loft",
    listed: "2026-07-29",
    title: p("Loft sa galerijom i kaminom u Petrovaradinu", "Loft with a gallery and fireplace in Petrovaradin"),
    summary: p("96 m² u preuređenom magacinu iz 1930, plafon 5,2 m, kamin na drva.", "96 m² in a converted 1930 warehouse, 5.2 m ceiling, wood-burning fireplace."),
    description: p(
      [
        "Nekadašnji magacin ispod tvrđave pretvoren je u tri lofta. Ovaj je najveći: otvoren prostor sa plafonom od 5,2 metra, stubovi od cigle i galerija sa spavaćim delom.",
        "Stan je trenutno rezervisan. Ako vas zanima sličan prostor, javite se: vodimo listu zainteresovanih kupaca za lofte.",
      ],
      [
        "A former warehouse below the fortress has been turned into three lofts. This is the largest: an open-plan space with a 5.2-metre ceiling, brick columns and a gallery with the sleeping area.",
        "The flat is currently reserved. If you'd like something similar, get in touch: we keep a list of buyers looking for lofts.",
      ],
    ),
    photos: [
      p("Loft sa kaminom i trpezarijom", "Loft with fireplace and dining"),
      p("Kamin i dnevni boravak", "Fireplace and lounge"),
      p("Otvoren prostor sa stepeništem", "Open plan with a staircase"),
      p("Stubovi od cigle", "Brick columns"),
      p("Galerija u potkrovlju", "Attic gallery"),
      p("Trpezarija", "Dining area"),
    ],
  },
  {
    id: "l13",
    slug: { sr: "dvosoban-stan-kod-stranda-liman", en: "two-room-flat-near-strand-liman" },
    deal: "rent",
    type: "apartment",
    hood: "liman",
    street: "Narodnog fronta",
    at: [545, 462],
    price: 780,
    area: 58,
    rooms: 2.0,
    floor: 2,
    floors: 4,
    year: 1974,
    renovated: 2023,
    heating: "district",
    features: ["registered", "furnished", "ac"],
    agent: "stefan",
    plan: "two",
    listed: "2026-09-19",
    title: p("Svetao dvosoban stan kod Štranda", "Bright two-room flat near Štrand"),
    summary: p("Namešten, 58 m², pet minuta do plaže i univerziteta. Od 15. oktobra.", "Furnished, 58 m², five minutes to the beach and university. From 15 October."),
    description: p(
      [
        "Stan je renoviran 2023. u svetlim tonovima sa hrastovim podovima. Dnevna soba i trpezarija su povezane, spavaća soba ima ugradni ormar od poda do plafona.",
        "Najam 780 € plus režije. Idealno za profesore, doktore iz Kliničkog centra ili par koji radi u centru.",
      ],
      [
        "Renovated in 2023 in light tones with oak floors. The living and dining rooms connect; the bedroom has a floor-to-ceiling wardrobe.",
        "Rent is €780 plus utilities. Ideal for lecturers, doctors at the Clinical Centre or a couple working in town.",
      ],
    ),
    photos: [
      p("Trpezarija", "Dining room"),
      p("Okrugli trpezarijski sto", "Round dining table"),
      p("Dnevna soba", "Living room"),
      p("Spavaća soba", "Bedroom"),
      p("Spavaća soba sa ormarom", "Bedroom with wardrobe"),
      p("Dnevni boravak", "Living area"),
    ],
  },
  {
    id: "l15",
    slug: { sr: "jednoiposoban-stan-izdavanje-detelinara", en: "one-bedroom-flat-to-rent-detelinara" },
    deal: "rent",
    type: "apartment",
    hood: "detelinara",
    street: "Ulica Kornelija Stankovića",
    at: [360, 192],
    price: 520,
    area: 44,
    rooms: 1.5,
    floor: 1,
    floors: 4,
    year: 1985,
    renovated: 2024,
    heating: "district",
    features: ["registered", "furnished", "parking"],
    agent: "stefan",
    plan: "onehalf",
    listed: "2026-09-08",
    title: p("Jednoiposoban stan za izdavanje, Detelinara", "One-bedroom flat to rent, Detelinara"),
    summary: p("Nova kuhinja, 44 m², parking u dvorištu. 520 € mesečno.", "New kitchen, 44 m², courtyard parking. €520 a month."),
    description: p(
      [
        "Stan ima potpuno novu kuhinju sa ugradnim aparatima, prostran ulazni hol sa garderoberom i kupatilo sa tuš kabinom. Polusoba je opremljena kao radna soba.",
        "Najam 520 € plus režije, depozit jedna kirija. Autobusi 4 i 12 staju ispred zgrade.",
      ],
      [
        "The flat has a brand-new kitchen with built-in appliances, a spacious entrance hall with a wardrobe and a bathroom with a walk-in shower. The half room is set up as a study.",
        "Rent is €520 plus utilities, one month's deposit. Buses 4 and 12 stop outside the building.",
      ],
    ),
    photos: [
      p("Bela kuhinja", "White kitchen"),
      p("Kuhinja sa radnim stolom", "Kitchen with a desk"),
      p("Kuhinja sa drvenom pločom", "Kitchen with a wooden worktop"),
      p("Ulazni hol", "Entrance hall"),
      p("Ulaz sa garderoberom", "Entrance with coat rack"),
      p("Ulazna vrata", "Front door"),
      p("Siva kuhinja", "Grey kitchen"),
    ],
  },
  {
    id: "l16",
    slug: { sr: "dvosoban-stan-izdavanje-grbavica", en: "two-room-flat-to-rent-grbavica" },
    deal: "rent",
    type: "apartment",
    hood: "grbavica",
    street: "Ulica Mileve Marić",
    at: [410, 402],
    price: 690,
    area: 55,
    rooms: 2.0,
    floor: 3,
    floors: 5,
    year: 2019,
    heating: "district",
    features: ["registered", "elevator", "furnished", "parking", "ac"],
    agent: "stefan",
    plan: "two",
    listed: "2026-09-22",
    title: p("Moderan dvosoban stan kod Promenade", "Modern two-room flat near Promenada"),
    summary: p("Novogradnja 2019, lift, parking mesto. Dostupno odmah.", "2019 new build, lift, parking space. Available now."),
    description: p(
      [
        "Minimalistički opremljen stan sa svetlim hrastovim podom, belom kuhinjom i dugačkim hodnikom sa ugradnim ormarima.",
        "Najam 690 € plus režije. Promenada je na pet minuta, Bulevar oslobođenja na tri.",
      ],
      [
        "A minimally furnished flat with pale oak floors, a white kitchen and a long hallway with built-in wardrobes.",
        "Rent is €690 plus utilities. Promenada mall is five minutes away, Liberation Boulevard three.",
      ],
    ),
    photos: [
      p("Ulaz ka kuhinji", "Entrance towards the kitchen"),
      p("Dnevna soba", "Living room"),
      p("Hodnik", "Hallway"),
      p("Hodnik sa klupom", "Hallway with bench"),
      p("Kuhinja", "Kitchen"),
      p("Kuhinja i hodnik", "Kitchen and hallway"),
    ],
  },
  {
    id: "l17",
    slug: { sr: "vila-sa-bazenom-cardak-sremska-kamenica", en: "villa-with-pool-sremska-kamenica" },
    deal: "sale",
    type: "house",
    hood: "sremska-kamenica",
    street: "Čardak",
    at: [455, 640],
    price: 780000,
    area: 310,
    plot: 1450,
    rooms: 6.0,
    floor: 0,
    floors: 2,
    year: 2023,
    heating: "heatpump",
    features: ["pool", "garden", "terrace", "parking", "registered", "ac", "storage"],
    agent: "jelena",
    badge: "exclusive",
    plan: "house",
    listed: "2026-09-26",
    title: p("Vila sa bazenom na Čardaku", "Villa with a pool on Čardak hill"),
    summary: p("310 m², plac od 1.450 m², bazen 12 × 4 m i pogled na grad.", "310 m², 1,450 m² plot, a 12 × 4 m pool and views over the city."),
    description: p(
      [
        "Vila je završena 2023. i od tada nije korišćena. Bazen dužine 12 metara prati liniju kuće, a sve sobe u prizemlju izlaze na drvenu terasu.",
        "Na spratu su četiri spavaće sobe sa kupatilima. Kuća ima pametni sistem za svetlo, grejanje i alarm, i agregat. Razgledanje samo uz prethodnu najavu.",
      ],
      [
        "The villa was completed in 2023 and has not been lived in since. The 12-metre pool follows the line of the house, and every ground-floor room opens onto the timber deck.",
        "Upstairs are four en-suite bedrooms. The house has a smart system for lighting, heating and security, and a backup generator. Viewings by appointment only.",
      ],
    ),
    photos: [
      p("Vila i bazen", "The villa and the pool"),
      p("Bazen ispred kuće", "Pool in front of the house"),
      p("Bazen uz dnevni boravak", "Pool beside the living room"),
      p("Terasa uz bazen", "Poolside terrace"),
      p("Trpezarija", "Dining room"),
      p("Trpezarija sa pogledom", "Dining room with a view"),
      p("Kupatilo od mermera", "Marble bathroom"),
    ],
  },
  {
    id: "l18",
    slug: { sr: "trosoban-stan-stara-zgrada-podbara", en: "three-room-flat-period-building-podbara" },
    deal: "sale",
    type: "apartment",
    hood: "podbara",
    street: "Kosovska",
    at: [760, 330],
    price: 214000,
    area: 76,
    rooms: 3.0,
    floor: 3,
    floors: 4,
    year: 1935,
    renovated: 2020,
    heating: "gas",
    features: ["registered", "storage"],
    agent: "marija",
    plan: "three",
    listed: "2026-08-20",
    title: p("Trosoban stan u zgradi iz 1935, Podbara", "Three-room flat in a 1935 building, Podbara"),
    summary: p("Toplo drvo, peć na drva i prozori na dve strane. 76 m².", "Warm timber, a wood stove and windows on two sides. 76 m²."),
    description: p(
      [
        "Stan ima prozore na dve strane, pa je provetren i svetao ceo dan. Vlasnici su sačuvali originalne podove od bora i dodali kuhinju sa drvenom pločom i peć na drva.",
        "Zgrada je renovirana 2020: novi krov, fasada i stepenište. Dunav i novi Žeželjev most su na pet minuta.",
      ],
      [
        "The flat has windows on two sides, so it is airy and bright all day. The owners kept the original pine floors and added a kitchen with a wooden worktop and a wood stove.",
        "The building was renovated in 2020: new roof, façade and stairwell. The Danube and the new Žeželj Bridge are five minutes away.",
      ],
    ),
    photos: [
      p("Dnevna soba", "Living room"),
      p("Kuhinja i trpezarija", "Kitchen and dining"),
      p("Spavaća soba", "Bedroom"),
      p("Kuhinja", "Kitchen"),
      p("Dnevni boravak sa peći", "Living room with a stove"),
      p("Uska kuhinja", "Galley kitchen"),
    ],
  },
];

export const listingById = (id: string) => listings.find((l) => l.id === id);
export const photoSrc = (l: Listing, i: number) => `/images/listings/${l.id}/${String(i + 1).padStart(2, "0")}.jpg`;
export const coverSrc = (l: Listing) => photoSrc(l, 0);

/** Elevation of the floor slab in metres (3.2 m per storey; houses sit at +0.45). */
export const listingKota = (l: Listing) => (l.type === "house" ? 0.45 : l.floor * 3.2);
