import type { Localized } from "@/lib/i18n";

const L = <T,>(sr: T, en: T): Localized<T> => ({ sr, en });

/** Copy for inner pages. */
export const listingsPage = {
  metaTitle: L("Nekretnine u Novom Sadu: stanovi i kuće na prodaju i za izdavanje", "Property in Novi Sad: flats and houses for sale and to rent"),
  metaDescription: L(
    "Pretražite stanove, garsonjere, penthause i kuće u Novom Sadu po kraju, ceni, kvadraturi i broju soba. Svaka nekretnina izmerena, sa osnovom i proverenim papirima.",
    "Search flats, studios, penthouses and houses in Novi Sad by neighbourhood, price, floor area and rooms. Every property measured, with a floor plan and checked paperwork.",
  ),
  label: L("Ponuda", "Listings"),
  title: L("Nekretnine", "Listings"),
  lead: L(
    "17 pažljivo odabranih stanova i kuća. Filtere možete podeliti linkom; mapa pokazuje gde je šta.",
    "17 carefully chosen flats and houses. Share your filters as a link; the map shows where everything is.",
  ),
  all: L("Sve", "All"),
  type: L("Vrsta", "Type"),
  hood: L("Kraj", "Neighbourhood"),
  price: L("Cena", "Price"),
  priceHint: L("Izaberite kupovinu ili najam da biste filtrirali po ceni.", "Choose buy or rent to filter by price."),
  area: L("Kvadratura od", "Floor area from"),
  anyArea: L("Bilo koja", "Any"),
  rooms: L("Sobe", "Rooms"),
  features: L("Mora da ima", "Must have"),
  more: L("Više filtera", "More filters"),
  less: L("Manje filtera", "Fewer filters"),
  filters: L("Filteri", "Filters"),
  reset: L("Poništi filtere", "Reset filters"),
  sort: L("Sortiraj", "Sort"),
  sorts: {
    new: L("Najnovije", "Newest"),
    "price-asc": L("Cena: od najniže", "Price: low to high"),
    "price-desc": L("Cena: od najviše", "Price: high to low"),
    "area-desc": L("Najveća kvadratura", "Largest first"),
  },
  views: { grid: L("Mreža", "Grid"), list: L("Lista", "List"), map: L("Mapa", "Map") },
  found: L("Pronađeno", "Found"),
  results: L("nekretnina", "properties"),
  none: L("Nema nekretnina za ove filtere.", "No properties match these filters."),
  noneHint: L(
    "Probajte širi raspon cene ili drugi kraj. Ili nam javite šta tražite, pa vas zovemo čim se pojavi.",
    "Try a wider price range or another neighbourhood. Or tell us what you're looking for and we'll call as soon as it comes up.",
  ),
  tellUs: L("Javite nam šta tražite", "Tell us what you need"),
  mapTitle: L("Mapa nekretnina u Novom Sadu", "Map of properties in Novi Sad"),
  share: L("Kopiraj link pretrage", "Copy search link"),
  copied: L("Link kopiran", "Link copied"),
  alertTitle: L("Niste našli pravi stan?", "Haven't found the one?"),
  alertText: L(
    "Polovina naših prodaja se desi pre nego što nekretnina uopšte izađe na sajt. Recite nam šta tražite i bićete prvi na listi.",
    "Half of our sales happen before a property even reaches the website. Tell us what you want and you'll be first on the list.",
  ),
};

export const listingPage = {
  perM2: L("po m²", "per m²"),
  facts: L("Osnovni podaci", "Key facts"),
  area: L("Površina", "Floor area"),
  rooms: L("Struktura", "Rooms"),
  floor: L("Sprat", "Floor"),
  kota: L("Kota poda", "Floor level"),
  year: L("Izgrađeno", "Built"),
  renovated: L("renovirano", "renovated"),
  heating: L("Grejanje", "Heating"),
  terrace: L("Terasa", "Terrace"),
  plot: L("Plac", "Plot"),
  status: L("Status", "Title"),
  registered: L("Uknjiženo", "Registered"),
  notRegistered: L("U postupku", "In progress"),
  floors: L("Spratnost", "Storeys"),
  features: L("Opremljenost", "Features"),
  about: L("O nekretnini", "About this home"),
  plan: L("Osnova", "Floor plan"),
  planNote: L("Ilustrativna osnova. Tačne mere dobijate uz dokumentaciju pre razgledanja.", "Illustrative plan. Exact measurements come with the paperwork before the viewing."),
  hood: L("Komšiluk", "Neighbourhood"),
  walk: L("Peške do", "Walking to"),
  min: L("min", "min"),
  guide: L("Vodič kroz kraj", "Neighbourhood guide"),
  mortgage: L("Kalkulator kredita", "Mortgage calculator"),
  rentCosts: L("Troškovi useljenja", "Move-in costs"),
  deposit: L("Depozit (1 kirija)", "Deposit (1 month)"),
  firstRent: L("Prva kirija", "First month's rent"),
  commission: L("Provizija agencije (50%)", "Agency fee (50%)"),
  utilities: L("Režije, okvirno mesečno", "Utilities, approx. per month"),
  moveIn: L("Ukupno za useljenje", "Total to move in"),
  book: L("Zakažite razgledanje", "Book a viewing"),
  bookLead: L(
    "Izaberite dan i termin. Agent vas zove u roku od dva sata da potvrdi, a dokumentaciju šaljemo pre razgledanja.",
    "Pick a day and a time. The agent calls within two hours to confirm, and we send the paperwork before the viewing.",
  ),
  agent: L("Vaš agent", "Your agent"),
  call: L("Pozovite", "Call"),
  write: L("Pišite", "Email"),
  share: L("Podelite", "Share"),
  similar: L("Slične nekretnine", "Similar homes"),
  back: L("Nazad na ponudu", "Back to listings"),
  gallery: {
    all: L("Sve fotografije", "All photos"),
    close: L("Zatvori galeriju", "Close gallery"),
    prev: L("Prethodna fotografija", "Previous photo"),
    next: L("Sledeća fotografija", "Next photo"),
    photo: L("Fotografija", "Photo"),
  },
  mortgageCopy: {
    title: L("Kalkulator kredita", "Mortgage calculator"),
    price: L("Cena nekretnine (€)", "Property price (€)"),
    down: L("Učešće", "Deposit"),
    rate: L("Kamatna stopa", "Interest rate"),
    years: L("Rok otplate", "Term"),
    monthly: L("Mesečna rata", "Monthly payment"),
    loan: L("Iznos kredita", "Loan amount"),
    interest: L("Kamata", "Interest"),
    total: L("Ukupno plaćeno", "Total paid"),
    principal: L("Glavnica", "Principal"),
    note: L(
      "Informativni obračun sa fiksnom kamatom. Tačnu ponudu daje banka nakon provere kreditne sposobnosti; rado vas povezujemo sa dve banke sa kojima radimo.",
      "Indicative, fixed-rate calculation. The exact offer comes from the bank after a credit check; we're happy to introduce you to the two banks we work with.",
    ),
    yearsUnit: L("god.", "yrs"),
  },
  viewing: {
    title: L("Zakažite razgledanje", "Book a viewing"),
    day: L("Dan", "Day"),
    time: L("Termin", "Time"),
    name: L("Ime i prezime", "Full name"),
    phone: L("Telefon", "Phone"),
    email: L("Email (opciono)", "Email (optional)"),
    message: L("Poruka (opciono)", "Message (optional)"),
    consent: L(
      "Slažem se da me Kota kontaktira u vezi sa ovim upitom. Podatke ne delimo sa trećim licima.",
      "I agree to be contacted by Kota about this enquiry. We never share your details with third parties.",
    ),
    submit: L("Pošalji zahtev", "Send request"),
    sending: L("Šaljem…", "Sending…"),
    errors: {
      name: L("Upišite ime i prezime.", "Please enter your name."),
      phone: L("Upišite broj telefona sa bar 8 cifara.", "Please enter a phone number with at least 8 digits."),
      email: L("Email adresa nije ispravna.", "That email address doesn't look right."),
      day: L("Izaberite dan.", "Choose a day."),
      time: L("Izaberite termin.", "Choose a time."),
      consent: L("Potrebna je vaša saglasnost.", "We need your consent."),
    },
    successTitle: L("Termin je rezervisan.", "Your viewing is booked."),
    successText: L(
      "Agent vas zove u roku od dva sata da potvrdi termin i pošalje dokumentaciju.",
      "The agent will call within two hours to confirm and send you the paperwork.",
    ),
    again: L("Zakaži još jedan termin", "Book another time"),
    sundayNote: L("Nedeljom razgledanja uz prethodnu najavu; agent potvrđuje dostupnost.", "Sunday viewings are by arrangement; the agent will confirm availability."),
    demoNote: L("Ovo je demo sajt, zahtev nije poslat.", "This is a demo site; no request was sent."),
  },
};

export const hoodsPage = {
  metaTitle: L("Kraj po kraj: vodič kroz naselja Novog Sada", "Neighbourhood guides: where to live in Novi Sad"),
  metaDescription: L(
    "Stari grad, Liman, Grbavica, Podbara, Petrovaradin i Sremska Kamenica: cene po kvadratu, škole, parkovi i kako se tu zaista živi.",
    "Old Town, Liman, Grbavica, Podbara, Petrovaradin and Sremska Kamenica: prices per m², schools, parks and what living there is really like.",
  ),
  label: L("Vodiči", "Guides"),
  title: L("Kraj po kraj", "Block by block"),
  lead: L(
    "Novi Sad je mali grad sa velikim razlikama. Deset minuta hoda deli austrougarski stan sa plafonom od 3,6 m i kuću sa bazenom na padini Fruške gore.",
    "Novi Sad is a small city with big differences. Ten minutes on foot separate an Austro-Hungarian flat with 3.6 m ceilings from a house with a pool on the slopes of Fruška Gora.",
  ),
  mapTitle: L("Mapa naselja Novog Sada", "Map of Novi Sad neighbourhoods"),
  read: L("Pročitaj vodič", "Read the guide"),
  alsoCovered: L("Radimo i na Detelinari i u Novom naselju", "We also cover Detelinara and Novo naselje"),
  lifeHere: L("Život ovde", "Life here"),
  avgPrice: L("prosečna cena po m²", "average price per m²"),
  schools: L("škola i vrtića", "schools & nurseries"),
  parks: L("parkova i šetališta", "parks & promenades"),
  cafes: L("kafića i restorana", "cafés & restaurants"),
  toCenter: L("min peške do Trga slobode", "min walk to Liberty Square"),
  center: L("vi ste u centru", "you're in the centre"),
  character: L("Karakter kraja", "Character"),
  gallery: L("Kadrovi iz kraja", "Around the neighbourhood"),
  onMap: L("Na mapi", "On the map"),
  listingsHere: L("Trenutno u ponudi", "Currently available"),
  noneHere: L("Trenutno nemamo nekretninu ovde, ali kupci sa naše liste traže baš ovaj kraj.", "We have nothing listed here right now, but buyers on our list are asking for exactly this area."),
  next: L("Sledeći kraj", "Next neighbourhood"),
  statsNote: L("Ilustrativni podaci na osnovu naših prodaja i javnih registara, 2026.", "Illustrative figures based on our sales and public registers, 2026."),
};

export const valuationPage = {
  metaTitle: L("Procena stana u Novom Sadu: koliko vredi vaš stan?", "Property valuation in Novi Sad: what is your home worth?"),
  metaDescription: L(
    "Besplatna online procena vrednosti stana ili kuće u Novom Sadu u pet koraka. Agent potvrđuje procenu u roku od 24 sata na osnovu stvarnih prodaja u vašoj ulici.",
    "Free online valuation for a flat or house in Novi Sad in five steps. An agent confirms it within 24 hours based on real sales in your street.",
  ),
  label: L("Procena", "Valuation"),
  title: L("Koliko vredi vaš stan?", "What is your home worth?"),
  lead: L(
    "Pet pitanja, dva minuta. Dobijate okvirni raspon odmah, a agent ga potvrđuje u roku od 24 sata.",
    "Five questions, two minutes. You get an estimated range right away, and an agent confirms it within 24 hours.",
  ),
  steps: [L("Kraj", "Area"), L("Kvadratura", "Size"), L("Sprat", "Floor"), L("Stanje", "Condition"), L("Dodaci", "Extras"), L("Rezultat", "Result")],
  q: {
    hood: L("Gde se nalazi nekretnina?", "Where is the property?"),
    area: L("Kolika je kvadratura?", "How big is it?"),
    areaHint: L("Neto površina iz lista nepokretnosti, bez terase.", "Net floor area from the title deed, excluding balconies."),
    floor: L("Na kom je spratu?", "Which floor is it on?"),
    condition: L("U kakvom je stanju?", "What condition is it in?"),
    extras: L("Šta još ima?", "What else does it have?"),
    result: L("Vaša okvirna procena", "Your estimated range"),
  },
  floors: {
    ground: L("Prizemlje / visoko prizemlje", "Ground / raised ground floor"),
    low: L("1. ili 2. sprat", "1st or 2nd floor"),
    mid: L("3. sprat i više, sa liftom", "3rd floor and up, with a lift"),
    top: L("Poslednji sprat, sa liftom", "Top floor, with a lift"),
    topNoLift: L("Poslednji sprat, bez lifta", "Top floor, no lift"),
    house: L("Kuća", "House"),
  },
  conditions: {
    renovate: [L("Za renoviranje", "Needs renovation"), L("Stare instalacije, stolarija, kupatilo.", "Old wiring, windows, bathroom.")],
    good: [L("Dobro stanje", "Good condition"), L("Useljivo, uredno, bez većih ulaganja.", "Ready to live in, no major work needed.")],
    renovated: [L("Renovirano", "Renovated"), L("Kompletna renovacija u poslednjih 5 godina.", "Full renovation within the last 5 years.")],
    new: [L("Novogradnja", "New build"), L("Zgrada mlađa od 5 godina ili prva prodaja.", "Building under 5 years old or first sale.")],
  },
  extras: {
    registered: L("Uknjiženo", "Registered title"),
    terrace: L("Terasa / lođa", "Balcony / terrace"),
    parking: L("Garaža ili parking mesto", "Garage or parking space"),
    elevator: L("Lift", "Lift"),
    view: L("Pogled na Dunav ili tvrđavu", "View of the Danube or fortress"),
    garden: L("Dvorište ili bašta", "Yard or garden"),
  },
  estimate: L("Okvirna vrednost", "Estimated value"),
  perM2: L("po m²", "per m²"),
  base: L("Osnova za kraj", "Area base"),
  adjust: L("Korekcije", "Adjustments"),
  cityScale: L("Gde ste u odnosu na grad", "Where you sit in the city"),
  cheapest: L("najpovoljnije", "lowest"),
  priciest: L("najskuplje", "highest"),
  next: L("Dalje", "Next"),
  back: L("Nazad", "Back"),
  confirm: L("Agent potvrđuje u roku od 24 sata", "An agent confirms within 24 hours"),
  confirmText: L(
    "Ostavite ime i broj, a Ana ili neko od agenata vas zove sa tri stvarne prodaje iz vaše ulice i preciznom procenom.",
    "Leave your name and number, and Ana or one of our agents will call with three real sales from your street and a precise figure.",
  ),
  send: L("Pošalji na potvrdu", "Send for confirmation"),
  successTitle: L("Primili smo vaš zahtev.", "We've got your request."),
  successText: L("Agent vas zove u roku od 24 sata, radnim danima obično za dva.", "An agent will call within 24 hours, usually within two on weekdays."),
  disclaimer: L(
    "Procena je ilustrativna i zasniva se na prosečnim cenama po kraju. Nije zvanična procena za banku ili sud.",
    "The estimate is illustrative and based on average prices per area. It is not an official valuation for a bank or court.",
  ),
  tableTitle: L("Ilustrativna tabela cena po m²", "Illustrative price table per m²"),
  tableHood: L("Kraj", "Area"),
  tableNote: L("Prosečne cene iz naših prodaja 2025–2026. Stvarna cena zavisi od zgrade, orijentacije i papira.", "Average prices from our 2025–2026 sales. The real price depends on the building, orientation and paperwork."),
};

export const sellPage = {
  metaTitle: L("Prodajte stan ili kuću u Novom Sadu", "Sell your flat or house in Novi Sad"),
  metaDescription: L(
    "Prodaja nekretnine sa Kotom: besplatna procena, provera papira, izmerena osnova, profesionalne fotografije i prosečna prodaja za 34 dana. Provizija 2%, samo ako prodamo.",
    "Selling with Kota: free valuation, paperwork check, measured floor plan, professional photography and an average sale in 34 days. 2% commission, only if we sell.",
  ),
  label: L("Za prodavce", "For sellers"),
  title: L("Prodajte sa nama.", "Sell with us."),
  lead: L(
    "Vaš stan zaslužuje više od tri fotografije sa telefona. Merimo, fotografišemo u pravo doba dana i dovodimo kupce koji su već provereni.",
    "Your home deserves more than three phone snapshots. We measure, photograph at the right hour and bring buyers who are already vetted.",
  ),
  stats: [
    { value: 34, suffix: "", label: L("dana prosečno do predugovora", "days on average to pre-contract") },
    { value: 97, suffix: "%", label: L("postignuto od tražene cene", "of asking price achieved") },
    { value: 640, suffix: "+", label: L("prodatih i izdatih nekretnina", "homes sold and let") },
    { value: 0, suffix: " €", label: L("ako ne prodamo", "if we don't sell") },
  ],
  processLabel: L("Proces", "Process"),
  processTitle: L("Šest koraka, jedan agent.", "Six steps, one agent."),
  steps: [
    {
      title: L("Procena", "Valuation"),
      text: L("Dolazimo u roku od 48 sati, gledamo stan i donosimo tri stvarne prodaje iz vaše ulice. Cenu predlažemo, vi odlučujete.", "We visit within 48 hours, view the home and bring three real sales from your street. We suggest a price; you decide."),
      image: "/images/listings/l10/02.jpg",
    },
    {
      title: L("Papiri", "Paperwork"),
      text: L("Proveravamo list nepokretnosti, terete, dozvole i usklađenost kvadrature. Ako nešto fali, sređujemo pre objave, ne posle ponude.", "We check the title deed, encumbrances, permits and registered floor area. If something is missing, we sort it before listing, not after an offer."),
      image: "/images/city/palata-trg.jpg",
    },
    {
      title: L("Merenje i osnova", "Measuring & floor plan"),
      text: L("Laserom merimo svaku prostoriju i crtamo osnovu. Kupci koji vide osnovu dolaze na razgledanje spremniji i ozbiljniji.", "We laser-measure every room and draw the plan. Buyers who see a floor plan arrive at viewings better prepared and more serious."),
      image: "/images/listings/l04/01.jpg",
    },
    {
      title: L("Fotografije i video", "Photography & video"),
      text: L("Fotograf dolazi kad sunce ulazi u dnevnu sobu. Uz to snimamo kratku video šetnju za kupce iz inostranstva.", "Our photographer comes when the sun reaches the living room. We also shoot a short video walkthrough for buyers abroad."),
      image: "/images/listings/l07/01.jpg",
    },
    {
      title: L("Razgledanja i pregovori", "Viewings & negotiation"),
      text: L("Vodimo sva razgledanja, filtriramo radoznale od kupaca i pregovaramo u vaše ime, uz pisani izveštaj posle svakog termina.", "We run every viewing, filter the curious from the serious and negotiate on your behalf, with a written report after each one."),
      image: "/images/listings/l11/04.jpg",
    },
    {
      title: L("Notar i ključevi", "Notary & keys"),
      text: L("Pripremamo predugovor, zakazujemo notara, pratimo uplatu i primopredaju. Posle ostajemo dostupni za svako pitanje.", "We prepare the pre-contract, book the notary, track the payment and handle the handover. Afterwards we're still a call away."),
      image: "/images/city/trg-slobode.jpg",
    },
  ],
  includedLabel: L("Uključeno u proviziju", "Included in the commission"),
  included: [
    L("Procena sa tri uporedne prodaje", "Valuation with three comparable sales"),
    L("Provera lista nepokretnosti i dozvola", "Title deed and permit check"),
    L("Laserski izmerena osnova", "Laser-measured floor plan"),
    L("Profesionalne fotografije i video šetnja", "Professional photos and video walkthrough"),
    L("Opis na srpskom i engleskom", "Descriptions in Serbian and English"),
    L("Objava na svim većim portalima", "Listing on every major portal"),
    L("Direktna ponuda kupcima sa naše liste", "Direct offer to buyers on our list"),
    L("Vođenje razgledanja i izveštaji", "Viewings run and reported"),
    L("Pregovori, predugovor i notar", "Negotiation, pre-contract and notary"),
  ],
  feeLabel: L("Provizija, jasno", "Commission, plainly"),
  feeTitle: L("2% i samo ako prodamo.", "2%, and only if we sell."),
  feeText: L(
    "Provizija je 2% od postignute cene plus PDV i plaća se tek na dan potpisivanja kupoprodajnog ugovora. Nema troškova oglašavanja, nema naknade ako se predomislite. Ugovor o posredovanju traje 90 dana i možete ga otkazati uz pisani otkaz od 15 dana.",
    "The commission is 2% of the achieved price plus VAT, paid only on the day the sale contract is signed. No advertising costs, no fee if you change your mind. The brokerage agreement runs for 90 days and can be cancelled with 15 days' written notice.",
  ),
  reviewsLabel: L("Prodavci o nama", "Sellers on us"),
  faqLabel: L("Pitanja prodavaca", "Seller questions"),
  ctaTitle: L("Počnimo od procene.", "Let's start with a valuation."),
  ctaText: L("Besplatno, bez obaveze. Za 24 sata znate realnu cenu svog stana.", "Free, no obligation. Within 24 hours you'll know your home's realistic price."),
};
